# Generated by Django 5.2.3 on 2025-12-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(default='Unknown', help_text='Comma-separated list of main actors', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Adventure', 'Adventure')], default='Action', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_length',
            field=models.CharField(default='0h 0m', help_text='Duration e.g. 2h 30m', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='review_stars',
            field=models.FloatField(default=0.0, help_text='Average rating out of 5'),
        ),
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
