# Generated by Django 6.0 on 2026-03-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_payment_id_successfulpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='expires_at',
        ),
    ]
