# Generated by Django 5.2.3 on 2025-12-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('video', models.FileField(upload_to='movies/')),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('Adventure', 'Adventure')], default='Action', max_length=50)),
                ('cast', models.CharField(default='Unknown', help_text='Comma-separated list of main actors', max_length=255)),
                ('movie_length', models.CharField(default='Unknown', help_text='Duration e.g. 2h 30m', max_length=20)),
                ('review_stars', models.FloatField(default=0.0, help_text='Average rating out of 5')),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
