# Generated by Django 5.2.3 on 2026-04-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_cast_alter_movie_genres_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinteraction',
            unique_together=set(),
        ),
    ]
